# Faktafrågor

## 1. I kapitlet beskrivs en checklista med sju steg. Beskriv de sju stegen översiktligt. I verkligheten, följs dessa steg i en rak progression eller arbetar man generellt sett mer iterativt?

> - ### Definiera Problemet
>   I detta steget skapar man sig en helhetsbild över vad för problem man ska lösa, samt varför och hur man ska lösa det. 
> - ### Få tillgång till datan
>   Här studerar man hur man använder datan och på vilka sätt man får använda den. Här sektionerar man också ut testdata som används vid ML-modellering. 
> - ### EDA
>   Här utforskar man hur datan ser ut, om det finns nåra icke numeriska kolumner, om det finns saknade värden. Man kollar efter vilka typer utav visualiseringar som är bäst för att förstå datan. 
> - ### Datahantering
>   Om vi hittat saknade värden eller icke numeriska kolumner, kan man hantera det här. Antingen tar man bort dom eller ersätter dom med något. Man kan också välja att hantera outliers eller data som är väldigt olik resten som i följande steg kan göra att visualiseringarna eller användandet av datan blir missvisande. Här väljer vi också ut vilka variabler eller egenskaper av datan vi vill eller inte vill använda utifrån vårat ändamål vilket kallas *feature engineering*.
> - ### ML-Modellering
>   I detta steget försöker vi hitta den bästa modellen för våran data. Detta kan vi göra med att utvärdera flera modeller med standardvärden för dess hyperparametrar. När vi hittat modellen som presterat bäst på valideringsdatan kan vi också applicera dess bäst presterande hyperparametrar. Man tränar till slut modellen på inte bara träningsdatan men också valideringsdatan och testar den mot testdatan.  
> - ### Presentera lösningen
>   Här presenterar vi datan med den visualisering som bäst för fram det budskap vi vill för de intressenter som vi har. Här får man tänka på målgrupp och anpassa visualiseringarna efter det. 
> - ### Produktionssättning och övervakning
>   I detta steg testar man om modellen presterar som den ska med olika typer av tester för att sedan produktionssätta den. Modellen kan efter tid behöva tränas om på ny data då den gamla kanske längre inte är lämplig eller representerar verkligheten.

## 2. Vad menas med att en modell produktionssätts?
>   Det betyder i princip att den ska användas för de saker den skapats för. Alltså om den tränats på att tyda huspriser baserat på olika faktorer så kommer den användas av ett företag för att beräkna framtida huspriser.

## 3. Vad är scikit-learn för något? Biblioteket följer några centrala designprinciper. Vilka är dessa? Vad är *estimators*, *predictors* och *transformers*?

>   Det är ett bibliotek för maskininlärningsalgoritmer och verktyg med öppen källkod(alltså att man kan se hur allt är kodat). 
>   - **Estimators** - Detta är ett objekt inom scikitlearn som lär sig, anpassar sig eller estimerar data genom .fit() metoden.  
>   - **Predictors** - Predictors bygger på estimators och innebär att ett estimator objekt som tränats på data kan prediktera eller gissa på den nya indatan.  
>   - **Transformers** - Transformers är estimators som har .transform() metoden. Detta görs för att all data inte kan användas av alla modeller och behöver därför ändras på för att modellen ska kunna lära sig utav den. 
>   ### Designprinciper:
>   - **Konsistens** - Alla tillvägagångsätt inom SKLearn följer samma mönster, från metoder i de olika klasserna till dokumentationen om dessa. 
>   - **Inspektion** - Man ska enkelt kunna inspektera en klass, dess metoder och modellers hyperparametrar. Man kan göra detta genom dokumentationen eller med `.get_params()` metoden.
>   - **Begränsning av klasser** - Klasser är reserverade för modellalgoritmer medans för data använder man Numpy arrays eller SciPy sparse matrices. Modellernas hyperparametrar som python strängar och siffror. 
>   - **Rimliga standardvärden för hyperparametrar** - SciKitlearn har rimliga standardvärden (default values) för hyperparametrar som gör att man inte behöver mata in värden om man inte behöver specifiera något.

## 4. Vad är *TensorFlow* och *Keras*?

>   TensorFlow är ett maskininlärningsbibliotek likt ScikitLearn men med ett större fokus på djupinlärning. Keras är ett snabbt och enkelt sätt att använda TensorFlow.

# Koduppgifter

In [13]:
## Tar bort sparade variabler och importer från föregående celler
%reset -f

## 9. Denna uppgift består av flera steg enligt nedan.

### **a)** Läs in datasetet “data_01.csv” med funktionen `read_csv()` från *Pandas*. Funktionen returnerar en ``DataFrame``.

#### Imports

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

In [15]:
df = pd.read_csv("../data/data_01.csv")

#### EDA

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      199 non-null    float64
 1   x2      199 non-null    float64
 2   x3      199 non-null    float64
 3   x4      199 non-null    float64
 4   x5      199 non-null    float64
 5   target  199 non-null    float64
dtypes: float64(6)
memory usage: 9.5 KB

- Inga icke-numeriska kolumner

In [17]:
df.head()

         x1        x2        x3        x4        x5      target
0  0.743487  1.072825  1.332911 -1.244771  0.344978  220.173943
1  0.835264  0.202184  0.966480  0.745883 -0.033773  175.873929
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224 -162.270054
3  1.210186  1.685258 -0.394123  0.719024 -2.166585  165.930461
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473   43.250511

### **b)** Dela upp datasetet i X och y.

In [18]:
y = df[["target"]]
X = df.drop(df.columns[-1],axis=1)

### **c)** Dela upp datan ytterligare, i ett träning-, ett validering-, och ett testset med ``train_test_split()``. Låt 20% av datan vara testdata och 15% av den återstående datan vara valideringsdata.

In [19]:
x_train_full, x_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=14)
# x_train_full bör vara 160
print(x_train_full.info())
x_train, x_val, y_train, y_val = train_test_split(x_train_full, y_train_full, test_size=0.15, random_state=14)
# 15%(validering) av 160(train_full) är 24
print(y_val.info())

<class 'pandas.DataFrame'>
Index: 159 entries, 171 to 107
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      159 non-null    float64
 1   x2      159 non-null    float64
 2   x3      159 non-null    float64
 3   x4      159 non-null    float64
 4   x5      159 non-null    float64
dtypes: float64(5)
memory usage: 7.5 KB
None
<class 'pandas.DataFrame'>
Index: 24 entries, 91 to 166
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   target  24 non-null     float64
dtypes: float64(1)
memory usage: 384.0 bytes
None

### **d)** Träna två valfria regressionsmodeller (exempelvis ``LinearRegression`` och ``DecisionTreeRegressor``) på träningsdatan. Notera, i kapitel 3 kommer vi lära oss mer om ``DecisionTreeRegressor``.

In [20]:
linear = LinearRegression()
linear.fit(x_train, y_train)

tree = DecisionTreeRegressor(random_state=14)
tree.fit(x_train, y_train)

DecisionTreeRegressor(random_state=14)

### **e)** Utvärdera modellerna på valideringsdatan.

In [21]:
def RMSE(y_true, y_pred):
    # gör till en dimensionella vektorer
    y_true = np.array(y_true).flatten()
    y_pred = np.array(y_pred).flatten()
    error_sum = 0
    for i in range(len(y_true)):
        error_sum += (y_true[i] - y_pred[i]) ** 2
    mean_error = error_sum / len(y_true)
    rmse = np.sqrt(mean_error)
    return rmse

In [22]:
## Utvärderar LinearRegression

linear_pred = linear.predict(x_val)
linear_rmse = RMSE(y_val, linear_pred)

# Utvärderar DecisionTree
hyper_params =  {'max_depth': (None, 10, 20, 30)}
grid = GridSearchCV(
    tree,
    hyper_params,
    scoring='neg_root_mean_squared_error',
    cv=5
)

grid.fit(x_train, y_train)
tree_pred = grid.predict(x_val)
tree_rmse = RMSE(y_val, tree_pred)

In [23]:
print("LinearRegression RMSE: ", linear_rmse)
print("DecisionTree RMSE: ", tree_rmse)
print("")
print("best depth:", grid.best_params_)
pd.DataFrame(grid.cv_results_)

LinearRegression RMSE:  3.236619481182467
DecisionTree RMSE:  95.022427874565

best depth: {'max_depth': 10}

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002017,0.000330,0.001477,0.000343,None,{'max_depth': None},-93.406971,-91.251713,-99.471704,-85.048168,-110.077595,-95.851230,8.477422,2
1,0.001710,0.000078,0.001225,0.000113,10,{'max_depth': 10},-90.127070,-91.789729,-98.822022,-87.139245,-108.950302,-95.365673,7.802473,1
2,0.001605,0.000040,0.001177,0.000075,20,{'max_depth': 20},-93.406971,-91.251713,-99.471704,-85.048168,-110.077595,-95.851230,8.477422,2
3,0.001668,0.000076,0.001128,0.000046,30,{'max_depth': 30},-93.406971,-91.251713,-99.471704,-85.048168,-110.077595,-95.851230,8.477422,2

*Max depth 10 verkar vara bäst, medans alla andra hamnar på samma andraplats*

### **f)** Träna om den bäst presterande modellen på både tränings- och valideringsdatan.

In [24]:
linear.fit(x_train_full, y_train_full)

LinearRegression()

### **g)** Utvärdera modellen på testdatan.

In [25]:
final_pred = linear.predict(x_test)


final_rmse = RMSE(y_test, final_pred)
print(final_rmse)

2.847747161389236

### **h)** Träna om modellen på hela datasetet.

In [26]:
linear.fit(X,y)

LinearRegression()